spring.datasource.url=jdbc:postgresql://localhost:5433/consultorio
spring.datasource.username=consultorio
spring.datasource.password=consultorio

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true