spring.datasource.url=jdbc:postgresql://localhost:5433/consultorio
spring.datasource.username=consultorio
spring.datasource.password=consultorio

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

clinica.horario.seg-a-sex-inicio=08:00
clinica.horario.seg-a-sex-fim=18:00
clinica.horario.sabado-inicio=08:00
clinica.horario.sabado-fim=12:00
clinica.horario.antecedencia-minima=30